### ISSUE TITLE
How can I send the form to the player?

### ISSUE THREAD

**Issue by SamuelPozzobon** [GiantQuartz/NpcDialog#1]

**Comment by SamuelPozzobon** [comment]
This is EntityDamageByEntity event:

        if($npc instanceof Quake){
            $event->setCancelled(true);
                $form = new DialogForm("Quake");

                $form->addButton(new Button("Coming Soon", function(Player $player) {
                    $player->sendMessage("Coming soon...");
                }));

                $form->setCloseListener(function(Player $player) {
                    $player->sendMessage("You closed the form!");
                });
                $form->pairWithEntity($npc);
            }

When I hit the entity it doesn't show up the form

**Comment by GiantQuartz** [comment]
Hi! When you right click (or hold an entity) the form should show up, attacking won't work.

**Comment by SamuelPozzobon** [comment]
Ah I tried, it works but the entity is bugged on the form

**Comment by GiantQuartz** [comment]
Can you show me how it looks like?

**Comment by SamuelPozzobon** [comment]
[https://imgur.com/1OgfN7n](url)

**Comment by GiantQuartz** [comment]
Yeah, that's a client-side issue, it only happens with the Human entities for some reason.

**Comment by SamuelPozzobon** [comment]
F

**Comment by SamuelPozzobon** [comment]
Thanks for your time!
